server:
  port: 7410
spring:
  application:
    name: order-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop_order?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.71.129
    port: 6379
    password: 1234
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: FULL  #自动映射的配置 属性和数据库列相同不用配置result
  global-config:      #逻辑删除的配置
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

seata:
  application-id: order
  enabled: true
  tx-service-group: order #和上面的nacos的上面的配置一致
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      namespace: a25b7948-5a66-4e7a-9bf6-db6e32f92086 #配置上面的namespace
      serverAddr: http://127.0.0.1:8848 #nacos地址
      group: SEATA_GROUP
      userName: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      serverAddr: http://127.0.0.1:8848
      group: SEATA_GROUP
      namespace: a25b7948-5a66-4e7a-9bf6-db6e32f92086
      userName: nacos
      password: nacos
      cluster: default
